# Generated by Django 5.0.6 on 2024-07-15 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='imageUrl',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='linkUrl',
            field=models.URLField(blank=True),
        ),
    ]
