# Generated by Django 5.0.7 on 2024-08-06 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_testimonials_testimonial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
